### ISSUE TITLE
Cloud of Bewilderment duration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [syrusgreycloak/nwn1grimoire#42]
```
Seems longer than 7 rounds with 8th level caster
```

Original issue reported on code.google.com by `ssbsy...@gmail.com` on 29 Jun 2009 at 5:28

**Comment by syrusgreycloak** [comment]
Duration as listed on p.48 of Spell Compendium is 1 round/level.  Code is set to 1 round per caster level.  Closing as won't fix.
